mqtt_host: 192.168.3.241

sensors:
  # See:
  #   https://github.com/flipdot/drinks-storage-mqtt
  #   https://github.com/flipdot/drinks-storage-state
  drinks-storage:
    topic: sensors/cellar/drinks_crate_counts
    const:
      category: beverage_supply
      location: cellar
      unit: crt
    mqtt:
      value: crate_count
      name: scale_name
  drinks-storage-raw:
    topic: sensors/cellar/drinks_scale_measurements_raw
    const:
      category: beverage_supply_raw
      location: cellar
      unit: raw
      name_prefix: esp_
    mqtt:
      value: scale_value
      name: esp_id
  heater:
    topic: sensors/heater/f391d8/fenster
    const:
      category: heater
      location: lounge
      unit: C
      name: lounge
    mqtt:
      value: temperature
  heater2:
    topic: sensors/heater/4c857f/fenster
    const:
      category: heater
      location: m-shop
      unit: C
      name: m-shop
    mqtt:
      value: temperature
  heater3:
    topic: sensors/heater/f376db/fenster
    const:
      category: heater
      location: raum4
      unit: C
      name: raum4
    mqtt:
      value: temperature

  heater-setpoint:
    topic: sensors/heater/f391d8/fenster
    const:
      category: heater_set_point
      location: lounge
      unit: C
      name: lounge
    mqtt:
      value: setpoint
  heater2-setpoint:
    topic: sensors/heater/4c857f/fenster
    const:
      category: heater_set_point
      location: m-shop
      unit: C
      name: m-shop
    mqtt:
      value: setpoint
  heater3-setpoint:
    topic: sensors/heater/f376db/fenster
    const:
      category: heater_set_point
      location: raum4
      unit: C
      name: raum4
    mqtt:
      value: setpoint

